language: python

python:
 - "2.7"

sudo: required

cache:
  apt: true
  pip: true
  directories:
    - $HOME/.cache/pip
    - $HOME/data
    - $HOME/disclosure-backend/data

env:
    global:
         - XDG_CACHE_HOME=$HOME/.cache/

before_install:
  - sudo apt-get install graphviz

install:
  - pip install python-coveralls nose-cov
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt

script: make test

after_success:
  - coveralls # Upload coverage to coveralls.io

deploy:
  provider: script
  script: make deploy
  on:
    branch: master
